# Water conflicts in the Colorado River Basin
### Week 2 - Discussion section

## 1. Archive Exploration
- Where was the data collected from?
    - Colorado River Basin ?
- During what time frame were the observations in the dataset collected
    - 2005-01-01 to 2021-12-31
- What was the author’s perceived value of this dataset?
    - Understanding social vulnerability, institutional resiliency, and water resource management

This dataset quantifies water-related conflicts in the Colorado River Basin from January 2005 to December 2021 in an effort to understand social vulnerability, institutional resiliency, and local water resource management.

Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, https://doi.org/10.5066/P9X6WR7J.

Data Accessed: Oct 7, 2026

In [2]:
import pandas as pd

df = pd.read_csv("data/Colorado River Basin Water Conflict Table.csv")

In [3]:
pd.set_option("display.max_columns", None)
df

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,2019.0,N,Y,Colorado Headwaters,140100,14,"Western Slope, CO",NaN,NaN,CO,8,Both,Water rights more generally,Board members of the Southwestern Waer Conserv...,"NGO, Conservation District, Agriculture, Business",0.0,Scored based on the fact that the discussion w...,NaN,0,0,3,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,2022.0,N,Y,Entire Colorado River Basin,NaN,"14, 15","Western Slope, CO",NaN,NaN,CO,8,Both,Drought; Water quality; Water rights more gene...,The event is a 'State of the River' event invo...,"Conservancy District, State Government, All Wa...",0.0,No true conflicts explored at this event. Pure...,NaN,2,1,5,0,0,0,0,1,0,0,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,2007.0,N,N,Entire Colorado River Basin,NaN,"14, 15","Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Conservation,Dept of Interior Secretary Dirk Kempthorne sig...,"All Water Users, Environment",5.0,Scored 5 based on the agreement to protect the...,NaN,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,2019.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Ground water depletion,The event is Arizona signing off on the Drough...,"Agriculture, State Government, Federal Government",4.0,Agreement signed and cooperation on all sides...,NaN,1,0,0,10,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0

In [4]:
df.shape

(268, 48)

In [5]:
df.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

In [6]:
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [7]:
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.0,268.000000,268.000000,268.0,268.0,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,4.600746,0.432836,0.0,0.011194,0.555970,0.0,0.0,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,4.006680,2.418554,0.0,0.105405,1.281035,0.0,0.0,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,4.500000,0.000000,0.0,0.000000,0.000000,0.0,0.0,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,7.000000,0.000000,0.0,0.000000,1.000000,0.0,0.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,26.000000,31.000000,0.0,1.000000,9.000000,0.0,0.0,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

In [9]:
df.isna().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [11]:
df['Issue Type'].value_counts()

Issue Type
Drought                                                                       66
Water rights more generally                                                   51
Conservation                                                                  43
Intergovernmental issues                                                      43
Infrastructure issues                                                         15
Water quality                                                                 10
Water transfers                                                                6
Instream water rights                                                          6
Flood                                                                          4
Intergovernmental issues: Water rights more generally                          2
Intergovernmental issues: Drought                                              1
Intergovernmental issues: Water transfers                                      1
Intergovernmental issues: Conservation                                         1
Conservation; Drought                                                          1
Fish passage                                                                   1
Ground water depletion                                                         1
Conservation; Water rights more generally                                      1
Drought; Water quality; Water rights more generally; Infrastructure issues     1
Conservation; Ground water depletion                                           1
Name: count, dtype: int64

In [20]:
df['Stakeholders'].value_counts()

Stakeholders
All Water Users                                                                                                                                                                                                   7
State Government, Federal Government                                                                                                                                                                              6
State Government, Federal Government, All Water Users                                                                                                                                                             6
Federal Government                                                                                                                                                                                                5
Federal Government, State Government                                                                                                                                                                              5
                                                                                                                                                                                                                 ..
State Government, Federal Government, Navajo Nation, Tohono O'Odham Nation, Pascua-Yaqui Tribe, Ak-Chin Indian Community, Gila River Indian Community, Private Utility, Irrigation Districts, Local Government    1
Environmental Groups, Gila River Indian Community, Agriculture, Federal Government, State Government, Business, All Water Users                                                                                   1
Agriculture, Local Government, State Government                                                                                                                                                                   1
State Government, All Water Users, Agriculture, Development, Recreation, Private Utility                                                                                                                          1
Agriculture, State Government, Federal Government                                                                                                                                                                 1
Name: count, Length: 199, dtype: int64

In [22]:
df['Place'].value_counts()

Place
Entire Colorado River Basin                                              19
State of Arizona                                                         17
Colorado River Basin                                                     13
Great Salt Lake                                                          10
Arizona                                                                   6
                                                                         ..
Gila River Indian Reservation                                             1
Navajo Nation, Hopi Reservation                                           1
AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation     1
Laughlin, AZ                                                              1
State of Arizona, State of California                                     1
Name: count, Length: 135, dtype: int64

In [23]:
df['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

## Using .str.split()

In [48]:
df['State'].str ## Must turn State column into series to apply .str.split

In [49]:
df['State'].str.split(';').explode().value_counts()

State
AZ     81
CO     39
UT     29
NV     12
 UT    11
CA      8
 CA     8
 NM     7
 NV     7
 WY     7
 CO     6
 AZ     6
NM      6
OH      1
WY      1
TX      1
Name: count, dtype: int64

# Examine State Codes

**Our goal today is to find which states are reported in the dataset as having water conflicts.**

1. Take a look at the non-NA values in the State column. HINT: notna() method for pandas.Series.

2. What could be a challenge to finding the states that have reported having water conflicts (without repetition)?

In [55]:
df.loc[df['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

If states are recorded together, i.e. "AZ; CA", then we risk either repeating or missing the record in our data analysis.

## Brainstorm
Individually, write down step-by-step instructions on how you would wrangle the data frame to obtain an array (without repetition) of the state codes in which a water conflict has been reported. Would you keep or remove NA values and why? It’s ok if you don’t know how to code each step - it’s way more important to have an idea of what you would like to do. :\

1. Split and explode state names, reassign to dataframe.
2. Remove space from States variables
3. Drop NAs- not giving us the info we need.
4. Filter 'Water Conflicts' to 'Y'
5. Count 'Y's per each State

In [56]:
# 1. Filter 'Water Conflicts' to 'Y'
states_conflict = df.loc[df['Conflict Present'] == 'Y', 'State']

In [58]:
# 2. Split and explode state names, reassign to dataframe.
states_split = states_conflict.str.split(';').explode()

In [61]:
# 3. Count 'Y's per each State, keep NAs
states_count = states_split.value_counts()
states_count

State
AZ     42
UT     21
CO     18
 UT     8
NV      8
 WY     5
 NM     5
 CA     5
NM      5
 NV     4
 CO     4
 AZ     3
CA      2
OH      1
WY      1
Name: count, dtype: int64